[package]
name = "xtask"
version = "4.12.3"
edition = "2024"

[dependencies]
cubecl-hip-sys = { path = "../crates/cubecl-hip-sys" }
bindgen = { workspace = true }
strum = { workspace = true }
log = { workspace = true }
tracel-xtask = { workspace = true }
